### ISSUE TITLE
TypeError: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by 1letter** [zopefoundation/DocumentTemplate#66] opened 2022-09-13 20:46 UTC
I use Plone 6. If i click in the portal_catalog on the Query Report Tab i get the following traceback:
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Shared.DC.Scripts.Bindings, line 333, in __call__
  Module Shared.DC.Scripts.Bindings, line 370, in _bindAndExec
  Module App.special_dtml, line 213, in _exec
  Module DocumentTemplate._DocumentTemplate, line 144, in render_blocks
  Module DocumentTemplate._DocumentTemplate, line 227, in render_blocks_
  Module DocumentTemplate._DocumentTemplate, line 245, in render_blocks_
  Module DocumentTemplate.DT_In, line 762, in renderwob
  Module DocumentTemplate._DocumentTemplate, line 144, in render_blocks
  Module DocumentTemplate._DocumentTemplate, line 245, in render_blocks_
  Module DocumentTemplate.DT_In, line 698, in renderwob
  Module DocumentTemplate.DT_In, line 853, in sort_sequence
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

**Comment by d-maurer** [comment] 2022-09-13 22:40
1letter wrote at 2022-9-13 13:46 -0700:
>I use Plone 6. If i click in the portal_catalog on the Query Report Tab i get the following traceback:
>```
>Traceback (innermost last):
> ...
>  Module DocumentTemplate.DT_In, line 853, in sort_sequence
>TypeError: '<' not supported between instances of 'dict' and 'dict'
>```

Even though the exception is raised in `DocumentTemplate`,
the issue is not caused by `DocumentTemplate`.
The cause is an improper (more precisely: Python 3 incompatible) use
of a document template, likely by `Products.ZCatalog`.

Check the URL; determine from its last component which
template has been used; search the source tree where this
template is defined and thereby which package is responsible
for the template.
Move this issue to the corresponding package.
Enhance the issue by the information you have found with
the analysis above.

**Comment by dataflake** [comment] 2022-09-14 05:18
Dieter is correct, the error is legitimate. Comparing dictionaries in Python 3 is not possible and will raise a `TypeError`. Python 2 did not.

From the traceback it looks like the template in question attempts to pass a sequence of dictionaries into a `<dtml-in>` and instructions to sort or reverse that sequence. That will not work under Python 3.

**Comment by 1letter** [comment] 2022-09-14 10:14
There is an open Issue in https://github.com/zopefoundation/Products.ZCatalog/issues/136

**Comment by dataflake** [comment] 2022-09-14 10:21
Closing as duplicate of https://github.com/zopefoundation/Products.ZCatalog/issues/136

**Closed by dataflake** 2022-09-14 10:21 UTC
Labels: duplicate, invalid
