### ISSUE TITLE
dtml-in fails to sort on unicode attribute in python2

### ISSUE THREAD

**Issue by remi-fastoche** [zopefoundation/DocumentTemplate#62] opened 2022-02-14 21:08 UTC
### What I did:
Running Zope4 with Python 2.7. (Yes this is a bit outdated)
Have a list of Zope objects with an attribute of type unicode or a property of type ustring.
For example, items in a Folder foo.
Then I have a DTML method containing:
```
<dtml-in "foo.objectValues()" sort=bar>
<dtml-var bar><br>
</dtml-in>
```
### What I expect to happen:
The values should be displayed in (alphabetical) order:
```
Alice
Bob
Charlie
```

### What actually happened:

The values are displayed in wrong order:
```
Charlie
Alice
Bob
```
(actually, they appear in reverse order of unsorted list)

### What version of Python and Zope/Addons I am using:
Python2.7
Zope4, all versions starting I believe at 4.0b5

### Analysis and proposed correction:
There is an old invisible bug coming from Zope2, in file DT_In.py.
The `basic_type` variable has `type('')` in the keys, but misses `type(u'')`.
In method `sort_sequence`, on a unicode string, `basic.type(k)` returns `False`, and an attempt is made to call the value, raising an exception. However the `except:` clause was a `pass` and the value for sorting was still the unicode string. That worked.

But in commit 22594 5th Oct 2018, the `except:` clause was changed to `k = _Smallest`, making all unicode values sorting the same.

**The proposed correction** is to _add the unicode type to `basic_types`_.
In Python2 both str and unicode will be recognised as basic types.
In Python3 `type('')` and `type(u'')` are the same thing, but it does not hurt.

**Comment by d-maurer** [comment] 2022-02-14 23:18
Self contained reproducible case:
```pycon
>>> from OFS.DTMLMethod import DTMLMethod
>>> dtml = DTMLMethod("m")
>>> dtml.manage_upload("<dtml-in lst mapping sort=key><dtml-var key></dtml-in>)")
>>> dtml(None, dict(lst=[dict(key=v) for v in u"1325"]))
u'5231)'
```

**Comment by d-maurer** [comment] 2022-02-15 00:18
`dtml-in` can only sort sequences when the sort values are either of a
"basic type" (currently `str`, `int`, `float`, `list` and `NoneType`)
or are callable.
If a sort value is not of a basic type, it is called to get the sort value;
if this fails, the sort value is sometimes (for single sort keys)
replaced by `_Smallest`.
This replacement is causing the bug.

The reported problem could be fixed by defining `unicode` as "basic type".
However, similar problems would still exist for other types, e.g. `decimal`.

I propose to replace the "basic type" logic by logic based on
`callable`: if the sort value is `callable`, try to call it and use
the result as sort value; if the call fails, keep the original sort value
(this may lead to an exception later on because callable values rarely support
comparisons).
The change would not be completely backward compatible: an application
might rely on the replacement of non basic, non callable sort values
by `_Smallest` (even though this apparently bahaves
like "larger than anything" (rather than "smaller than anything")).

**Comment by remi-fastoche** [comment] 2022-02-16 21:30
I agree that testing if the key is callable has advantages:

- basic types list is difficult to maintain, it may evolve with versions of Python (that was the initial cause for the current issue)
- it is better to test "callability" before trying to call. If callable and an exception is raised it means the call fails, and taking the smallest value makes sense. If not callable it is either a basic type or hopefully a comparable type.

So just changing the test `if not basic_type(type(k))` by `if callable(k)` would make it.
(and basic_types can go away)

**Comment by icemac** [comment] 2023-07-18 07:39
I am closing this old issue as Python 2 is no longer supported.

**Closed by icemac** 2023-07-18 07:39 UTC
